//// <auto-generated />
//using System;
//using LLMService.DataAccess;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace LLMService.Migrations
//{
//    [DbContext(typeof(LLMServiceDbContext))]
//    partial class LLMServiceDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.9")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("LLMService.Entities.ChatMessage", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("AnalysisType")
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<string>("Content")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("IsUserMessage")
//                        .HasColumnType("bit");

//                    b.Property<int>("SessionId")
//                        .HasColumnType("int");

//                    b.Property<string>("StockSymbol")
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)");

//                    b.Property<DateTime>("Timestamp")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("SessionId");

//                    b.HasIndex("Timestamp");

//                    b.ToTable("ChatMessages");
//                });

//            modelBuilder.Entity("LLMService.Entities.ChatSession", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("LastActivityAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("SessionName")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.HasKey("Id");

//                    b.HasIndex("CreatedAt");

//                    b.HasIndex("UserId");

//                    b.ToTable("ChatSessions");
//                });

//            modelBuilder.Entity("LLMService.Entities.ChatMessage", b =>
//                {
//                    b.HasOne("LLMService.Entities.ChatSession", "Session")
//                        .WithMany("Messages")
//                        .HasForeignKey("SessionId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Session");
//                });

//            modelBuilder.Entity("LLMService.Entities.ChatSession", b =>
//                {
//                    b.Navigation("Messages");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
